#!/usr/bin/env node
/**
 * Pin this package to a Zig release.
 *
 *   node scripts/update-zig.ts            # latest stable release
 *   node scripts/update-zig.ts 0.16.0     # a specific release
 *
 * Fetches the official release index, records every prebuilt target's archive
 * URL, size and SHA-256 in zig-release.json, snapshots the community mirror
 * list, and sets the package version to match. Review the diff, then publish.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import type { Release, ReleaseTarget } from "../lib/install.ts";

const INDEX_URL = "https://ziglang.org/download/index.json";
const MIRRORS_URL = "https://ziglang.org/download/community-mirrors.txt";
// Zig Software Foundation release signing key, from https://ziglang.org/download/
const PUBLIC_KEY = "RWSGOq2NVecA2UPNdBUZykf1CCb147pkmdtYxgb3Ti+JO/wCYvhbAb/U";

/** Shape of one release in https://ziglang.org/download/index.json. */
interface IndexArtifact {
  tarball: string;
  shasum: string;
  size: string;
}
interface IndexRelease {
  version?: string;
  date: string;
  docs: string;
  stdDocs?: string;
  notes?: string;
  [target: string]: IndexArtifact | string | undefined;
}

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const requested = process.argv[2];

const index = (await (await fetch(INDEX_URL)).json()) as Record<
  string,
  IndexRelease
>;
const stable = Object.keys(index)
  .filter((k) => /^\d+\.\d+\.\d+$/.test(k))
  .sort((a, b) => {
    const pa = a.split(".").map(Number),
      pb = b.split(".").map(Number);
    return (
      (pa[0] ?? 0) - (pb[0] ?? 0) ||
      (pa[1] ?? 0) - (pb[1] ?? 0) ||
      (pa[2] ?? 0) - (pb[2] ?? 0)
    );
  });
const version = requested && requested !== "latest" ? requested : stable.at(-1);
const entry = version ? index[version] : undefined;
if (!version || !entry) {
  console.error(
    `Zig ${version} not found in ${INDEX_URL}. Known releases: ${stable.join(", ")}`,
  );
  process.exit(1);
}
if (!/^\d+\.\d+\.\d+$/.test(version)) {
  console.error(
    `"${version}" is not a stable release; this package only tracks stable releases.`,
  );
  process.exit(1);
}

const targets: Record<string, ReleaseTarget> = {};
for (const [key, value] of Object.entries(entry)) {
  if (
    typeof value !== "object" ||
    value === undefined ||
    key === "src" ||
    key === "bootstrap"
  ) {
    continue;
  }
  if (!value.tarball.startsWith("https://ziglang.org/download/")) {
    throw new Error(`unexpected tarball URL for ${key}: ${value.tarball}`);
  }
  if (!/^[0-9a-f]{64}$/.test(value.shasum)) {
    throw new Error(`bad shasum for ${key}`);
  }
  targets[key] = {
    tarball: value.tarball,
    shasum: value.shasum,
    size: Number(value.size),
  };
}

const mirrorsText = await (await fetch(MIRRORS_URL)).text();
const mirrors = mirrorsText
  .split("\n")
  .map((l) => l.trim())
  .filter((l) => /^https:\/\//.test(l));
if (mirrors.length === 0) {
  throw new Error("empty mirror list");
}

const releaseFile: Release & { "//": string } = {
  "//": "Generated by scripts/update-zig.ts from https://ziglang.org/download/index.json. Do not edit by hand.",
  version,
  date: entry.date,
  notes: entry.notes ?? "",
  publicKey: PUBLIC_KEY,
  mirrorsSnapshotDate: new Date().toISOString().slice(0, 10),
  mirrors,
  targets,
};
fs.writeFileSync(
  path.join(root, "zig-release.json"),
  `${JSON.stringify(releaseFile, null, 2)}\n`,
);

const pkgPath = path.join(root, "package.json");
const pkg = JSON.parse(fs.readFileSync(pkgPath, "utf8")) as { version: string };
pkg.version = version;
fs.writeFileSync(pkgPath, `${JSON.stringify(pkg, null, 2)}\n`);

console.log(
  `Pinned Zig ${version} (released ${entry.date}): ${Object.keys(targets).length} targets, ${mirrors.length} mirrors.`,
);
console.log(`Package version: ${pkg.version}`);
console.log(`Release notes: ${entry.notes}`);
